version: 2

models:
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        data_type: varchar
        constraints:
          - type: not_null
      - name: product_name
        data_type: varchar
      - name: product_type
        data_type: varchar
      - name: product_description
        data_type: varchar
      - name: product_price
        data_type: float
      - name: is_food_item
        data_type: boolean
      - name: is_drink_item
        data_type: boolean
